import React,{createContext,useContext,useEffect,useState,ReactNode}from'react';
import{UserProfile,UserRole}from'../types';
import{supabase}from'../lib/supabase';
interface AuthContextType{currentUser:UserProfile|null;isAuthenticated:boolean;isAdmin:boolean;isOperator:boolean;users:UserProfile[];pendingUsers:UserProfile[];pendingApprovalsCount:number;isLoading:boolean;login:(i:string,p:string)=>Promise<any>;quickLoginAs:(r:'ADMIN'|'OPERADOR',id?:string)=>Promise<boolean>;logout:()=>void;registerUserRequest:(d:any)=>Promise<any>;createUser:(d:any)=>Promise<any>;approveUser:(id:string,r?:UserRole)=>Promise<any>;rejectUser:(id:string,m?:string)=>Promise<any>;updateUser:(id:string,d:Partial<UserProfile>)=>Promise<any>;deleteUser:(id:string,p?:string)=>Promise<any>;deleteOwnAccount:(p:string)=>Promise<any>;changePassword:(id:string,p:string)=>Promise<any>;toggleUserActive:(id:string)=>Promise<any>;resetUsersToDefault:(p?:string)=>Promise<any>}
const C=createContext<AuthContextType|undefined>(undefined);
const role=(r:string):UserRole=>r==='admin'||r==='supervisor'?'ADMIN':'OPERADOR';
const profile=(p:any):UserProfile=>({id:p.id,name:p.full_name||p.email||'Usuário',username:p.email?.split('@')[0]||p.id,graduacao:p.graduacao||'PM',re:p.re||'',pelotao:p.pelotao||'ROCAM',role:role(p.role),passwordHash:'',salt:'',createdAt:p.created_at,isActive:p.active!==false,status:p.active===false?'INATIVO':'ATIVO'});
const email=(s:string)=>s.includes('@')?s.trim().toLowerCase():`${s.trim().toLowerCase()}@rocam.local`;
export const AuthProvider:React.FC<{children:ReactNode}>=({children})=>{
 const[u,setU]=useState<UserProfile[]>([]),[me,setMe]=useState<UserProfile|null>(null),[loading,setLoading]=useState(true);
 const load=async(id?:string)=>{if(id){const{data}=await supabase.from('profiles').select('*').eq('id',id).single();setMe(data?.active!==false&&data?profile(data):null)}const{data}=await supabase.from('profiles').select('*').order('created_at');if(data)setU(data.map(profile))};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>load(data.session?.user.id).finally(()=>setLoading(false)));const{data}=supabase.auth.onAuthStateChange((_e,s)=>{load(s?.user.id)});return()=>data.subscription.unsubscribe()},[]);
 const login=async(i:string,p:string)=>{const{error}=await supabase.auth.signInWithPassword({email:email(i),password:p});return error?{success:false,error:error.message}:{success:true}};
 const logout=()=>{supabase.auth.signOut();setMe(null)};
 const quickLogin=async(r:'ADMIN'|'OPERADOR',id?:string)=>!!me&&(id?me.id===id:me.role===r);
 const register=async(d:any)=>{const{data,error}=await supabase.auth.signUp({email:email(d.username),password:d.password,options:{data:{full_name:d.name}}});if(error)return{success:false,error:error.message};if(data.user)await supabase.from('profiles').update({full_name:d.name}).eq('id',data.user.id);return{success:true}};
 const create=async(d:any)=>{if(me?.role!=='ADMIN')return{success:false,error:'Apenas Administrador.'};const r=await supabase.functions.invoke('admin-create-user',{body:{email:email(d.username),password:d.password,full_name:d.name,role:d.role==='ADMIN'?'admin':'operador'}});if(r.error)return{success:false,error:r.error.message};await load();return{success:true}};
 const approve=async(id:string,r?:UserRole)=>{if(me?.role!=='ADMIN')return{success:false,error:'Acesso negado.'};const{error}=await supabase.from('profiles').update({active:true,role:r==='ADMIN'?'admin':'operador'}).eq('id',id);if(error)return{success:false,error:error.message};await load();return{success:true}};
 const reject=async(id:string)=>{if(me?.role!=='ADMIN')return{success:false,error:'Acesso negado.'};const{error}=await supabase.from('profiles').update({active:false}).eq('id',id);if(error)return{success:false,error:error.message};await load();return{success:true}};
 const update=async(id:string,d:Partial<UserProfile>)=>{if(me?.role!=='ADMIN')return{success:false,error:'Acesso negado.'};const{error}=await supabase.from('profiles').update({full_name:d.name,active:d.isActive}).eq('id',id);if(error)return{success:false,error:error.message};await load(me?.id);return{success:true}};
 const toggle=async(id:string)=>{if(me?.role!=='ADMIN')return{success:false,error:'Acesso negado.'};const x=u.find(v=>v.id===id);if(!x)return{success:false,error:'Usuário não encontrado.'};const{error}=await supabase.from('profiles').update({active:!x.isActive}).eq('id',id);if(error)return{success:false,error:error.message};await load();return{success:true}};
 const change=async(id:string,p:string)=>{if(id!==me?.id)return{success:false,error:'Acesso negado.'};const{error}=await supabase.auth.updateUser({password:p});return error?{success:false,error:error.message}:{success:true}};
 const deny=async()=>({success:false,error:'Operação disponível pelo administrador do Supabase.'});
 const pending=u.filter(x=>x.status==='PENDENTE');
 return <C.Provider value={{currentUser:me,isAuthenticated:!!me,isAdmin:me?.role==='ADMIN',isOperator:me?.role==='OPERADOR',users:u,pendingUsers:pending,pendingApprovalsCount:pending.length,isLoading:loading,login,quickLoginAs:quickLogin,logout,registerUserRequest:register,createUser:create,approveUser:approve,rejectUser:reject,updateUser:update,deleteUser:deny,deleteOwnAccount:deny,changePassword:change,toggleUserActive:toggle,resetUsersToDefault:deny}}>{children}</C.Provider>
};
export const useAuth=()=>{const x=useContext(C);if(!x)throw Error('useAuth must be used within AuthProvider');return x};
